# Generated by Django 6.0.2 on 2026-03-03 19:15

import task_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[task_manager.models.validate_task_deadline]),
        ),
    ]
